### ISSUE TITLE
Support for nested hyperparameters

### ISSUE THREAD

**Issue by bigeagle** [megvii-research/hpman#3]
It is quite common to have a nested config file for being more readable. 

For example, the author have a yaml config like this：
```yaml
discriminator:
  in_channels: 3
  spectral: true
  norm: 'instance'
  activation: 'leaky_relu'
  residual: true
  input_size: [512, 512]
```

Support nested hyperparameter definition could extend the realm of this library further.
